config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "games#index"

  get :signup, to: "users#new"
  resources :users, only: :create

  get :login, to: "sessions#new"
  delete :logout, to: "sessions#destroy"
  resources :sessions, only: :create

  resources :games do
    resources :reviews, shallow: true, only: [ :create, :destroy, :update, :edit ]
  end

  resources :marketplaces, only: [ :index, :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_marketplaces, dependent: :destroy
  has_many :marketplaces, through: :game_marketplaces
  has_many :reviews, dependent: :destroy

  has_and_belongs_to_many :genres, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/game_marketplace.rb
class GameMarketplace < ApplicationRecord
  belongs_to :game
  belongs_to :marketplace

  validates :price, presence: true
  validates :steam_id, uniqueness: true, allow_nil: true
  validates :xbox_id, uniqueness: true, allow_nil: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games

  validates :name, presence: true, uniqueness: true
end

app/models/marketplace.rb
class Marketplace < ApplicationRecord
  has_many :game_marketplaces
  has_many :games, through: :game_marketplaces

  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true, url: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :game
  belongs_to :user

  validates :body, presence: true
  validates :user_id, uniqueness: { scope: :game_id, message: "You have already reviewed this game" }
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEX = /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/.freeze

  has_many :reviews, dependent: :destroy

  has_secure_password

  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGEX }
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    helper_method :current_user, :logged_in?, :authenticate_user!
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def authenticate_user!
    redirect_to login_path, alert: "You must be logged in to perform that action" unless logged_in?
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show]

  def index
    @view_type = params[:view_type] || "tile"
    @games = Game.all
  end

  def show
    @reviews = @game.reviews.where.not(id: nil)
    @review = @game.reviews.new
  end

  private

  def set_game
    @game = Game.includes(:reviews).find(params[:id])
  end
end

app/controllers/marketplaces_controller.rb
class MarketplacesController < ApplicationController
  before_action :set_marketplace, only: :show

  def index
    @marketplaces = Marketplace.all
  end

  def show; end

  private

  def set_marketplace
    @marketplace = Marketplace.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [ :create ]
  before_action :set_game, only: [ :create ]
  before_action :set_review, only: [ :destroy, :update, :edit ]

  def create
    @review = @game.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      render turbo_stream: turbo_stream.append("reviews", partial: "reviews/review", locals: { review: @review })
    else
      render turbo_stream: turbo_stream.replace("errors", partial: "shared/errors", locals: { resource: @review })
    end
  end

  def update
    if @review.update(review_params)
      render turbo_stream: turbo_stream.replace("edit-review-#{@review.id}", partial: "reviews/review", locals: { review: @review })
    else
      render turbo_stream: turbo_stream.replace("errors", partial: "shared/errors", locals: { resource: @review })
    end
  end

  def edit
    render turbo_stream: turbo_stream.replace("review-#{@review.id}", partial: "reviews/edit", locals: { review: @review })
  end

  def destroy
    render turbo_stream: turbo_stream.remove("review-#{@review.id}") if @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:body, :game_id, :user_id)
  end

  def set_game
    @game = Game.find(params[:game_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in successfully"
    else
      redirect_to login_path, alert: "Invalid email or password"
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: "Logged out successfully"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "User created successfully"
    else
      render turbo_stream: turbo_stream.replace("errors", partial: "shared/errors", locals: { resource: @user })
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :nickname, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_game_list_view.html.slim
.grid.gap-4.sm:grid-cols-1.md:grid-cols-1.lg:grid-cols-1
  - games.each do |game|
    .game-item id="game-#{game.id}"
      = link_to game.name, game_path(game), data: { turbo: false }, class: "block p-4 bg-white rounded-lg shadow-md hover:shadow-lg transition duration-300 ease-in-out text-center"

app/views/games/_game_show.html.slim
header.game-header.mb-6.border-b.border-gray-200.pb-2
  h1.game-name.text-4xl.font-bold.text-gray-900 = @game.name

.game-details.mb-6
  .mb-4
    h3.game-description.text-lg.font-medium.text-gray-700.mb-1 Description:
    p.text-gray-600 = @game.description
  .mb-2
    h3.game-release-date.text-md.font-medium.text-gray-700.mb-1 Release Date:
    p.text-gray-600 = @game.released_at
  .mb-2
    h3.game-developer.text-md.font-medium.text-gray-700.mb-1 Developer:
    p.text-gray-600 = @game.developer
  .mb-2
    h3.game-publisher.text-md.font-medium.text-gray-700.mb-1 Publisher:
    p.text-gray-600 = @game.publisher

.game-genres.mb-6
  h3.text-lg.font-semibold.text-gray-700.mb-3 Genres:
  ul.list-disc.ml-6
    - @game.genres.each do |genre|
      li.game-genre.text-gray-600 = genre.name

.game-price.mb-6
  h3.text-lg.font-semibold.text-gray-700.mb-3 Price:
  - @game.game_marketplaces.each do |marketplace|
    .mb-2
      h4.text-md.font-medium.text-gray-700.mb-1 = marketplace.marketplace.name
      p.text-xl.text-green-600 = marketplace.price

app/views/games/_game_tile_view.html.slim
.grid.gap-4.sm:grid-cols-2.md:grid-cols-3.lg:grid-cols-5
  - games.each do |game|
    .game-item id="game-#{game.id}"
      = link_to game.name, game_path(game), data: { turbo: false }, class: "block p-4 bg-white rounded-lg shadow-md hover:shadow-lg transition duration-300 ease-in-out"

app/views/games/index.html.slim
.games
  .container.mx-auto.p-4
    h1.text-2xl.font-bold.mb-4 = 'Games'
    .flex.justify-end
      = form_tag games_path, method: :get, id: "view-type-select", data: { turbo_frame: "games_view_type" } do
        select#view-type name="view_type" onchange="this.form.requestSubmit()"
          option(value="tile" selected=(@view_type == "tile")) Tile
          option(value="list" selected=(@view_type == "list")) List

    = turbo_frame_tag 'games_view_type' do
      - if @view_type == "tile"
        = render partial: "games/game_tile_view", locals: { games: @games }
      - else
        = render partial: "games/game_list_view", locals: { games: @games }

app/views/games/show.html.slim
.game-show
  .container.mx-auto.p-4 id="game-#{@game.id}"
    = render "games/game_show"

    .reviews-container
      .w-1/2.mx-auto.p-4
        h2 = "Reviews:"
      = turbo_frame_tag "reviews" do
        - if @reviews.present?
          - @reviews.each do |review|
            = render "reviews/review", review: review

      = render "reviews/form", game: @game, review: @review, form_url: game_reviews_path(@game), form_method: :post

app/views/layouts/application.html.slim
doctype html
html
  head
    title = content_for(:title) || "App"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    meta name="mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    // Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    // tag.link rel: "manifest", href: pwa_manifest_path(format: :json)

    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"

    // Includes all stylesheet files in app/assets/stylesheets
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = render "shared/navbar"
    - if notice
      .w-fit.mx-auto.bg-green-100.border.border-green-400.text-green-700.px-4.py-3.rounded.relative
        span.font-bold.mr-2 &#9888;
        = notice

    - if alert
      .w-fit.mx-auto.bg-red-100.border.border-red-400.text-red-700.px-4.py-3.rounded.relative
        span.font-bold.mr-2 &#9888;
        = alert

    = yield

app/views/marketplaces/_marketplace.html.slim
= link_to marketplace.name, marketplace_path(marketplace), class: "block p-4 bg-white rounded-lg shadow-md hover:shadow-lg transition duration-300 ease-in-out"

app/views/marketplaces/_marketplace_show.html.slim
- if @marketplace.logo_url.present?
  .mr-4
    a href=@marketplace.url target="_blank"
      img.max-h-20 src=@marketplace.logo_url alt="#{@marketplace.name} logo"
.flex-1.flex.flex-col.items-center
  h1.text-4xl.font-bold.mb-2.border-b-2.border-gray-300 = @marketplace.name
  p.text-lg.mb-4
    a.text-blue-500.hover:underline href=@marketplace.url target="_blank" = @marketplace.url

app/views/marketplaces/index.html.slim
h2.text-2xl.font-bold.mb-4 Marketplaces

.marketplaces-container.grid.gap-4.sm:grid-cols-2.md:grid-cols-3.lg:grid-cols-4
  - @marketplaces.each do |marketplace|
    = render "marketplace", marketplace: marketplace

app/views/marketplaces/show.html.slim
.marketplace-show
  .container.mx-auto.p-4.flex.items-start id="marketplace-#{@marketplace.id}"
    = render "marketplace_show"

app/views/reviews/_edit.html.slim
turbo-frame id="edit-review-#{review.id}"
  .w-1/2.mx-auto.mb-4.bg-white.rounded-lg.shadow-md
    .p-4
      = form_with model: review, remote: true, class: "space-y-6" do |form|
        = render "shared/errors", resource: review
        .field
          = form.label :body, class: "block text-sm font-medium text-gray-700"
          .mt-1
            = form.text_area :body, class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md", rows: 3
          .mt-2.flex.justify-end
            = form.submit "Submit", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/reviews/_form.html.slim
.w-1/2.mx-auto.mb-4.bg-white.rounded-lg.shadow-md
  .p-4
    = form_with model: [ game, review ], url: form_url, method: form_method, class: "space-y-6" do |form|
      = render "shared/errors", resource: review
      .field
        = form.label :body, class: "block text-sm font-medium text-gray-700"
        .mt-1
          = form.text_area :body, placeholder: "Leave your review", class: "shadow-sm focus:ring-indigo-500 focus:border-indigo-500 mt-1 block w-full sm:text-sm border border-gray-300 rounded-md", rows: 3
        .mt-2.flex.justify-end
          = form.submit "Submit", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

app/views/reviews/_review.html.slim
turbo-frame id="review-#{review.id}"
  .w-1/2.mx-auto.mb-4.bg-white.rounded-lg.shadow-md
    .p-4
      .flex.items-start.justify-between
        .flex-1
          .text-sm.font-medium.text-gray-900
            = review.user.nickname
          .text-xs.font-light.text-gray-500.mt-1
            = review.created_at.strftime("%b %d, %Y")
        .flex-1.text-right
          .text-sm.font-medium.text-gray-900
            = review.body

      - if current_user&.id == review.user_id
        .flex.justify-end.mt-2
          .text-sm.font-medium.text-gray-900
            = link_to "Edit", edit_review_path(review), remote: true, class: "text-blue-500 hover:text-blue-700 mr-2"
            = link_to "Delete", review_path(review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-red-500 hover:text-red-700"

app/views/shared/_errors.html.slim
= turbo_frame_tag "errors" do
  - if resource.errors.any?
    .error-messages
      .bg-red-100.border.border-red-400.text-red-700.px-4.py-3.rounded.relative
        ul.list-disc.ml-5
          - resource.errors.full_messages.each do |message|
            li = message

app/views/shared/_navbar.html.slim
nav.navbar
  .bg-gray-800.p-4.flex.justify-between.items-center
    .text-white.text-xl.font-bold
      | AndRBuZ Games
    ul.nav-list
      .flex.space-x-4.text-lg
        li.nav-item
          = link_to "Home", root_path, class: "text-white hover:text-gray-300"
        li.nav-item
          = link_to "Marketplace", marketplaces_path, class: "text-white hover:text-gray-300"
    ul.nav-list.nav-auth
      .flex.space-x-4.text-lg
        - if logged_in?
          li.nav-item
            = link_to "Logout", logout_path, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-white hover:text-gray-300"
        - else
          li.nav-item
            = link_to "Login", login_path, class: "text-white hover:text-gray-300"
          li.nav-item
            = link_to "Signup", signup_path, class: "text-white hover:text-gray-300"

app/views/users/_form.html.slim
= form_with model: @user, url: form_url, method: form_method, class: "space-y-4 max-w-md mx-auto p-6 border rounded shadow-md" do |form|
  = render "shared/errors", resource: @user
  .field
    = form.label :nickname, class: "block font-medium text-gray-700 mb-1"
    .relative
      .absolute.left-0.pl-3.flex.items-center.pointer-events-none.top-1/2.-translate-y-1/2
        svg.h-5.w-5.text-gray-400 fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
          path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
      = form.text_field :nickname, class: "mt-2 block w-full rounded-md border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 pl-10"

  .field
    = form.label :email, class: "block font-medium text-gray-700 mb-1"
    .relative
      .absolute.left-0.pl-3.flex.items-center.pointer-events-none.top-1/2.-translate-y-1/2
        svg.h-5.w-5.text-gray-400 fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
          path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
      = form.email_field :email, class: "mt-2 block w-full rounded-md border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 pl-10"

  .field
    = form.label :password, class: "block font-medium text-gray-700 mb-1"
    .relative
      .absolute.left-0.pl-3.flex.items-center.pointer-events-none.top-1/2.-translate-y-1/2
        svg.h-5.w-5.text-gray-400 fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
          path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
      = form.password_field :password, class: "mt-2 block w-full rounded-md border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 pl-10"

  .field
    = form.label :password_confirmation, class: "block font-medium text-gray-700 mb-1"
    .relative
      .absolute.left-0.pl-3.flex.items-center.pointer-events-none.top-1/2.-translate-y-1/2
        svg.h-5.w-5.text-gray-400 fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"
          path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
      = form.password_field :password_confirmation, class: "mt-2 block w-full rounded-md border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 pl-10"

  .actions
    = form.button button_text, class: "text-white bg-gradient-to-r from-cyan-400 via-cyan-500 to-cyan-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 shadow-lg shadow-cyan-500/50 dark:shadow-lg dark:shadow-cyan-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2"

app/views/users/new.html.slim
h2.text-2xl.font-bold.mb-4.text-center Sign Up

.signup-container
  = render "form", user: @user, form_url: users_path, form_method: :post, button_text: "Sign Up"